[[project]]
name = "Example Project"
description = "A disk based KV store (based on Bitcask implementation)"
links = [
  { name = "Blog", url = "https://mrkaran.dev/posts/barreldb/" },
  { name = "GitHub", url="https://github.com/mr-karan/barreldb" },
]
